config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :books, shallow: true do 
    resources :recommendations
  end

  resources :users, shallow: true do 
    resource :profile, only: [:show]
    resource :club
    
    resources :friendships
  end
  
  resource :profile, only: [:new, :create, :edit, :update, :destroy]
  
  root to: "static#query"
  
  get 'static/query'
  post 'static/search', as: :book_search
  
  post 'users/:user_id/toggle_friendship', to: "friendships#toggle_friendship", as: :toggle_friendship
  
  post 'users/find', to: "users#find", as: :find_user
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :recommentations

  validates :title, :author, :asin, presence: true
end

app/models/club.rb
class Club < ActiveRecord::Base
  belongs_to :owner, class_name: User
  
  delegate :members, to: :owner
  
  validates :owner, presence: true
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user, class_name: User
  belongs_to :friend, class_name: User
  
  validates :user, :friend, presence: true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  
  validates :user, presence: true
  # validates :name, :location, :bio, presence: true
end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
  belongs_to :recommender, class_name: User
  belongs_to :book
  belongs_to :club
  
  validates :recommender, :book, :club, presence: true
  validates :description, :inscription, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_one :profile
         
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
   
  has_one  :club, foreign_key: :owner_id, dependent: :destroy
  
  has_many :recommendations, dependent: :destroy
  has_many :recommended_books, through: :recommendations, source: :book
  
  has_many :subscriptions, through: :friends, source: :club

  alias_method :members, :friends

  def befriend(user)
    unless self.friends.include?(user)
      self.friends << user
      user.friends << self
    end
  end
   
  def defriend(user)
    if self.friends.include?(user)
      Friendship.find_by(user: self, friend: user).destroy
      Friendship.find_by(user: user, friend: self).destroy
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def index
    @friends = current_user.friends
  end

  def toggle_friendship 
    @user = User.find(params[:user_id])
    if @user.friends.include? current_user
      @user.defriend(current_user)
      render json: { friend: false }
    else
      @user.befriend(current_user)
      render json: { friend: true }
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @user = current_user
    @profile = Profile.new(user: @user)
  end
  
  def create
    @user = current_user
    @profile = Profile.new(user: @user)
    @profile.attributes = profile_params
    
    if @profile.save
      redirect_to @user
    else
      render :new
    end
  end
  
  def edit
    @user = current_user
    @profile = @user.profile
  end
  
  def update
    @user = current_user
    @profile = @user.profile
    
    if @profile.update(profile_params)
      redirect_to @user
    else
      render :new
    end
  end
  
  private
  
  def profile_params
    params.require(:profile).permit(:name, :location, :bio)
  end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def query
    
  end
  
  def search
    @title = params[:title].empty? ? nil : "intitle:#{URI::escape params[:title]}"
    @author = params[:author].empty? ? nil : "inauthor:#{URI::escape params[:author]}"
    @join = (@title && @author) ? "+" : nil
    
    @url = "https://www.googleapis.com/books/v1/volumes?q=#{@title}#{@join}#{@author}"
    @response = HTTParty.get(@url)
    
    @items = @response['items'].take(5).map do |item|
      volume_info = item['volumeInfo'] || {}
      image_links = volume_info['imageLinks'] || {
        'thumbnail' => 'http://lorempixel.com/150/200',
        'smallThumbnail' => 'http://lorempixel.com/150/200'
      }
      isbn = volume_info["industryIdentifiers"].select { |id| id['type'] == "ISBN_13" }.first['identifier']
      
      {
        title: volume_info['title'],
        authors: volume_info['authors'],
        publication_year: volume_info['publishedDate'],
        image_url: image_links['thumbnail'],
        small_image_url: image_links['smallThumbnail'],
        isbn: isbn
      }
    end
    
    # render json: JSON.pretty_generate(@items)
    
    # @url = "https://www.goodreads.com/search/index.xml?key=#{ENV['good_reads_key']}&q=#{URI.escape params[:title]}+#{URI.escape params[:author]}"
    # @response = HTTParty.get(@url)
    #
    # @items = @response["GoodreadsResponse"]["search"]["results"]["work"].map do |item|
    #   book = item["best_book"]
    #
    #   {
    #     title: book["title"],
    #     author: book["author"]["name"],
    #     publication_year: item["original_publication_year"],
    #     image_url: book["image_url"],
    #     small_image_url: book["small_image_url"]
    #   }
    #end
  end
  
  private
  
  def search_params
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @profile = @user.profile
    
    if @user == current_user && !@profile
      redirect_to new_profile_url
    else
      render :show
    end
  end
  
  def friends
    @users = current_user.friends
  end
  
  def find
    @user = User.find_by(email: params[:user][:email])
    
    if @user
      redirect_to @user
    else
      redirect_to request.referer
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_page(path)
    "active_page" if current_page?(path)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def profile_display(value)
    if value.nil? || value.empty?
      "<code>[redacted]</code>".html_safe
    else
      value
    end
  end
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def star_class(user)
    user.friends.include?(current_user) ? "friend" : ""
  end
end

app/views/application/_header.html.erb
<header class="navigation">
  <nav class="primary clearfix">
    <div class="brand">
      <a href="/">
        My Friends' Book Club
      </a>
    </div>
    <ul class="navs right">
      <li>
        <%= link_to "Users", current_user %>
      </li>
      <li>
        <% if user_signed_in? %>
          <%= link_to "Sign Out", destroy_user_session_url, method: :delete %>
        <% else %>
          <%= link_to "Sign In / Up", new_user_session_url %>
        <% end %>
      </li>
    </ul>
  </nav>
  <%= render partial: "navbar_context" %>
</header>

<% if notice || alert %>
  <section class="information">
    <% if notice %>
      <div class="alert alert-warning">
        <%= notice %>
      </div>
    <% end %>

    <% if alert %>
      <div class="alert alert-danger">
        <%= alert %>
      </div>
    <% end %>
  </section>
<% end %>

app/views/friendships/index.html.erb
<% @friends.each do |friend| %>
  <%= render partial: 'users/profile', locals: { profile: friend.profile } %>
<% end %>

<script>
$('i.fa-star').on('click', function (e) {
  var $star = $(this);
  var userId = $star.data('id');
  var url = "/users/" + userId + "/toggle_friendship";
  
  $.post(url, function(data) {}).done(function(data) { 
    $star.toggleClass('friend');
  });
});
</script>

app/views/profiles/_form.html.erb
<section class="profile">
  <%= form_for profile, url: profile_path do |p| %>
    <fieldset class="form-group">
      <%= p.label :name, "Your Name" %>
      <%= p.text_field :name, placeholder: "Matthew Short" %>
    </fieldset>
    <fieldset class="form-group">
      <%= p.label :location, "Location" %>
      <%= p.text_field :location, placeholder: "Brooklyn, NY" %>
    </fieldset>
    <fieldset class="form-group">
      <%= p.label :bio, "Biography" %>
      <%= p.text_field :bio, placeholder: "I <3 books!  I want >3 books!" %>
    </fieldset>
    <%= submit_tag "Search" %>
  <% end %>
</section>

app/views/profiles/_navbar_context.html.erb
<nav class="contextual clearfix">
  <div class="search left">
    <%= form_tag find_user_url, method: :post do %>
      <%= text_field_tag "user_email", nil, type: :text, placeholder: "Find a user by email address", name: "user[email]" %>
      <%= button_tag do %>
        <i class="fa fa-search"></i>
      <% end %>
    <% end %>
  </div>
  <ul class="navs right">
    <li>
      <%= link_to "Your Page", user_url(current_user) %>
    </li>
    <li>
      <%= link_to "Your Friends", user_friendships_url(current_user) %>
    </li>
  </ul>
</nav>

app/views/profiles/edit.html.erb
<%= render partial: 'form', locals: { user: current_user, profile: @profile } %>

app/views/profiles/new.html.erb
<%= render partial: 'form', locals: { user: current_user, profile: @profile } %>

app/views/users/_profile.html.erb
<section class="profile">
  <h5>
    <%= user.email %>
    <% if user == current_user %>
      <span class="right">
        <%= link_to "Edit", edit_profile_url %>
      </span>
    <% else %>
      <span class="right">
        <i class="fa fa-star <%= star_class(user) %>" data-id="<%= user.id %>"></i>
      </span>
    <% end %>
  </h5>
  
  <% profile ||= Profile.new(user: user) %>
  
  <div class="profile-element">
    <h4>
      Name
    </h4>
    <p>
       <%= profile_display profile.name %>
    </p>
  </div>
  <div class="profile-element">
    <h4>
      Location
    </h4>
    <p>
      <%= profile_display profile.location %>
    </p>
  </div>
  <div class="profile-element last-element">
    <h4>
      Biography
    </h4>
    <p>
      <%= profile_display profile.bio %>
    </p>
  </div>
</section>

app/views/users/friends.html.erb
<% @friends.each do |friend| %>
  <%= render partial: 'users/profile', locals: { user: friend, profile: friend.profile } %>
<% end %>

<script>
$('i.fa-star').on('click', function (e) {
  var userId = $(this).data('id');
  var url = "/users/" + userId + "/toggle_friendship";
  
  $.post(url, function(data) {}).done(function(data) { 
    $star.toggleClass('friend');
  });
});
</script>

app/views/users/show.html.erb
<%= render partial: 'profile', locals: { profile: @profile, user: @user } %>

<script>
  $('i.fa-star').on('click', function (e) {
    var $star = $(this);
    var userId = $star.data('id');
    var url = "/users/" + userId + "/toggle_friendship";
  
    $.post(url, function(data) {}).done(function(data) { 
      $star.toggleClass('friend');
    });
  });
</script>